# Copyright (c) 2026 Hygon Information Technology Co., Ltd.
# SPDX-License-Identifier: Apache-2.0
name: Quality Gate

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - deepep-backend

permissions:
  contents: read

concurrency:
  group: quality-gate-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  checks:
    name: Checks
    uses: HYGON-AI/quality-gate/.github/workflows/pr-quality-gate.yml@v2.0.3
    with:
      runner_labels: '["self-hosted","Linux","X64","ci","bw20","bw1000"]'
    permissions:
      contents: read
